# Generated by Django 5.0.2 on 2024-02-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('description', models.TextField(max_length=105)),
                ('image', models.ImageField(upload_to='images/service/')),
            ],
        ),
    ]
