# Generated by Django 5.0.2 on 2024-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PAY', 'PAY'), ('RETURN', 'RETURN')], max_length=100, null=True),
        ),
    ]
